// Generated by CoffeeScript 1.9.3
(function() {
  var path, transformTools;

  path = require('path');

  transformTools = require('browserify-transform-tools');

  module.exports = transformTools.makeStringTransform("shaderify", {
    includeExtensions: ['.glsl']
  }, function(content, opts, done) {
    var result;
    result = null;
    if (content != null) {
      result = "module.exports = " + (JSON.stringify(content));
    }
    return done(null, result);
  });

}).call(this);
